### ISSUE TITLE
Test out unit tests

### ISSUE THREAD

**Issue by agstephens** [cedadev/mule_build#1]
@alaniwi: to progress this further, please test out the unit tests, as follows...

You can run the unit tests if you have Python’s `unittest `module… e.g.

```
python –m unittest discover –v um_packing.tests
```

(and the same for the other modules – not all of them have unit tests but the main ones do)

**Comment by alaniwi** [comment]
- `mule.tests` - ran 264 tests, one failed

```
ERROR: test_ff_to_pp_var_grid (mule.tests.unit.test_pp.Test_load_fields)                                                                                                                              
----------------------------------------------------------------------                                                                                                                                
Traceback (most recent call last):                                                                                                                                                                    
  File "/var/tmp/mule_build/installed/mule_env/lib/python3.8/site-packages/mule-2018.7.1-py3.8.egg/mule/tests/unit/test_pp.py", line 119, in test_ff_to_pp_var_grid                                   
    fields_to_pp_file(temp_path, ff.fields, ff)                                                                                                                                                       
  File "/var/tmp/mule_build/installed/mule_env/lib/python3.8/site-packages/mule-2018.7.1-py3.8.egg/mule/pp.py", line 300, in fields_to_pp_file                                                        
    grid_type = field.stash.grid                                                                                                                                                                      
AttributeError: 'NoneType' object has no attribute 'grid'                                                                                                                                             
```

- `um_packing.tests` - ran 3 tests, all passed

- `um_spiral_search.tests` - ran 6 tests, all passed

- `um_sstpert` - no tests

- `um_utils` - 62 tests, 7 failures.  All these failures appear to be trivial issues regarding float formatting, but the test will need to be fixed.  Example:
```
 : Lines not equal:
Found:
  'Maximum RMS diff as % of data in file 1: 382.9708431025352 (field 4)'
Expected:
  'Maximum RMS diff as % of data in file 1: 382.97084310253518 (field 4)'
```



- `um_wafccb` - no tests
